### ISSUE TITLE
do you have any plan to support wav2vec?

### ISSUE THREAD

**Issue by firdota** [ELS-RD/transformer-deploy#37]
hello, do you have any plan to support wav2vec?

**Comment by pommedeterresautee** [comment]
Hi, not on the short term, what feature are you interested in? Deploy, GPU quantization, something else?

**Comment by firdota** [comment]
deploy. I want to speed up the inference. Thanks for your reply and look forward to the new feature!

**Comment by salamer** [comment]
any progress?

**Comment by pommedeterresautee** [comment]
Not yet, we are working on seq2seq right now :-)

**Comment by salamer** [comment]
or any advice? I think I can contribute, but at the moment I don't have the relevant direction for this.

and an other question, would you consider provide some C++ deployment toolkit in the future? because if the performance really matters, C++ or Rust would be a natural choice.

**Comment by pommedeterresautee** [comment]
I don't know if C++ matters that much if you deploy on Triton (C++).
Triton itself is in charge of the inference, the Python code is just here to call the tokenizer (Rust) and request the inference engine.
The only exception is generative model, because the greedy / beam search part is a bit slow (Pytorch code mainly, but AFAIK you can do better in pure C++). However, search part is tiny compared to the decoder part, so it's not really a priority for us.
Moreover, there are more interesting opportunities like using a tokenizer running on GPU (Nvidia has released one).

Regarding contribution, I would gladly help you.
Can you implement something abstracting the inference part, just a kind of wrapper following HF conventions that can reuse some ONNX model for instance? like in https://github.com/ELS-RD/transformer-deploy/blob/main/src/transformer_deploy/utils/generative_model.py#L44 ?
If you do that and provide an example on ho to use it, I can rework it and support this family of models in the library.
